artifact_uri: /Users/nicholaspate/Documents/01_Active/ATLAS/backend/ATLAS_Enhanced/353764387557323550/683ed314ed3f4cb3b06cd0fa179fcc6d/artifacts
end_time: 1759037400313
entry_point_name: ''
experiment_id: '353764387557323550'
lifecycle_stage: active
run_id: 683ed314ed3f4cb3b06cd0fa179fcc6d
run_name: chat_c430549e
source_name: ''
source_type: 4
source_version: ''
start_time: 1759037400304
status: 3
tags: []
user_id: nicholaspate
